language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest --ignore-platform-reqs"
    - COMPOSER_FLAGS="--ignore-platform-reqs"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update  --no-progress --no-interaction --no-suggest --prefer-source $COMPOSER_FLAGS

script:
  - mkdir -p build/logs
  - vendor/bin/phpcs
  - vendor/bin/phpmd config,src text phpmd.xml
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

branches:
  only:
    - master

notifications:
  email: false